// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfoacs8bIY-mLDvqUuCRifp3KcOdajYGk',
    appId: '1:482332102323:web:019a96a117fedd1a1ceac6',
    messagingSenderId: '482332102323',
    projectId: 'jadwalku-e8085',
    authDomain: 'jadwalku-e8085.firebaseapp.com',
    storageBucket: 'jadwalku-e8085.firebasestorage.app',
    measurementId: 'G-CRN402VWBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC09EU-XbckpnYuDILsb2u4uEIezj5puM',
    appId: '1:482332102323:android:98e23d9b82b99ef81ceac6',
    messagingSenderId: '482332102323',
    projectId: 'jadwalku-e8085',
    storageBucket: 'jadwalku-e8085.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnLMqhovR8r0aDCo0vFiOubb3OcbuoltU',
    appId: '1:482332102323:ios:7751221635a3738c1ceac6',
    messagingSenderId: '482332102323',
    projectId: 'jadwalku-e8085',
    storageBucket: 'jadwalku-e8085.firebasestorage.app',
    iosBundleId: 'com.jadwalku.app',
  );
}
